package gui;

import exceptions.EntidadNoAptaParaCursadaException;
import exceptions.NoEstaEntidadException;

import java.awt.Dimension;
import java.awt.Toolkit;

import java.util.HashMap;

import java.util.Iterator;

import javax.swing.DefaultListModel;

import javax.swing.JFrame;

import javax.swing.JOptionPane;

import pga.Alumno;
import pga.Controlador;
import pga.Cursada;

/**
 *
 * @author manuc
 */
public class AlumnoAltaACursada2 extends javax.swing.JDialog
{
    private Controlador controlador;
    private Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    private HashMap<String, Alumno> hash1;
    private HashMap<String, Cursada> hash2;
    private DefaultListModel listModel1, listModel2;
    private Alumno alumno;    
    private Cursada cursada;

    /** Creates new form AlumnoAltaACursada2 */
    public AlumnoAltaACursada2(java.awt.Frame parent, boolean modal, Controlador controlador)
    {
        super(parent, modal);
        this.controlador = controlador;
        this.setTitle("Alumno - Alta a Cursada");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setResizable(false);
        initComponents();
        this.setLocation(d.width / 2 - this.getWidth() / 2, d.height / 2 - this.getHeight() / 2);
        this.setVisible(true);
    }
    
    public boolean camposVaciosA()
    {
        return !(this.jTextFieldNombre1.getText().length() != 0 && this.jTextFieldApellido1.getText().length() != 0);
    }
    
    public void listar1(HashMap<String, Alumno> hash)
    {
        Iterator <Alumno> iA = hash.values().iterator();
        
        this.listModel1.clear();
        while(iA.hasNext())
            this.listModel1.addElement(iA.next());
        this.jList1.setModel(this.listModel1);
    }
    
    public boolean camposVaciosC()
    {
        return this.jTextFieldNombre2.getText().length() == 0;
    }
    
    public void listar2(HashMap<String, Cursada> hash)
    {
        Iterator <Cursada> iC = hash.values().iterator();
        
        this.listModel2.clear();
        while(iC.hasNext())
            this.listModel2.addElement(iC.next());
        this.jList2.setModel(this.listModel2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jButtonBuscar1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listModel1 = new DefaultListModel();
        jList1 = new javax.swing.JList<>();
        jButtonElegir1 = new javax.swing.JButton();
        jLabelAlumno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombre2 = new javax.swing.JLabel();
        jTextFieldNombre2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        listModel2 = new DefaultListModel();
        jList2 = new javax.swing.JList<>();
        jButtonBuscar2 = new javax.swing.JButton();
        jButtonElegir2 = new javax.swing.JButton();
        jLabelCursada = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelAlumnoAlta1 = new javax.swing.JLabel();
        jLabelDatosAlumnoAlta1 = new javax.swing.JLabel();
        jLabelCursadaAlta1 = new javax.swing.JLabel();
        jLabelDatosCursadaAlta1 = new javax.swing.JLabel();
        jButtonDarAlta = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombre1.setText("Nombre");

        jLabelApellido1.setText("Apellido");

        jTextFieldApellido1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldApellido1ActionPerformed(evt);
            }
        });

        jTextFieldNombre1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldNombre1ActionPerformed(evt);
            }
        });

        jButtonBuscar1.setText("Buscar");
        jButtonBuscar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscar1ActionPerformed(evt);
            }
        });

        jList1.setModel(listModel1);
        jScrollPane3.setViewportView(jList1);

        jButtonElegir1.setText("Elegir");
        jButtonElegir1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonElegir1ActionPerformed(evt);
            }
        });

        jLabelAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAlumno.setText("Alumnos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApellido1)
                            .addComponent(jLabelNombre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonElegir1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelAlumno)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido1)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar1)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButtonElegir1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombre2.setText("Nombre");

        jList2.setModel(listModel2);
        jScrollPane4.setViewportView(jList2);

        jButtonBuscar2.setText("Buscar");
        jButtonBuscar2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscar2ActionPerformed(evt);
            }
        });

        jButtonElegir2.setText("Elegir");
        jButtonElegir2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonElegir2ActionPerformed(evt);
            }
        });

        jLabelCursada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCursada.setText("Cursadas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCursada)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelNombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonElegir2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jLabelCursada)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre2)
                            .addComponent(jTextFieldNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar2)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButtonElegir2)
                .addGap(12, 12, 12))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAlumnoAlta1.setText("Alumno");

        jLabelDatosAlumnoAlta1.setText("Elija un alumno");

        jLabelCursadaAlta1.setText("Cursada");

        jLabelDatosCursadaAlta1.setText("Elija una cursada");

        jButtonDarAlta.setText("Dar alta");
        jButtonDarAlta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDarAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlumnoAlta1)
                    .addComponent(jLabelCursadaAlta1))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDatosAlumnoAlta1)
                    .addComponent(jLabelDatosCursadaAlta1))
                .addGap(32, 32, 32)
                .addComponent(jButtonDarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAlumnoAlta1)
                            .addComponent(jLabelDatosAlumnoAlta1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCursadaAlta1)
                            .addComponent(jLabelDatosCursadaAlta1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonDarAlta)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButtonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void jTextFieldApellido1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldApellido1ActionPerformed
    {//GEN-HEADEREND:event_jTextFieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido1ActionPerformed

    private void jTextFieldNombre1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldNombre1ActionPerformed
    {//GEN-HEADEREND:event_jTextFieldNombre1ActionPerformed

    }//GEN-LAST:event_jTextFieldNombre1ActionPerformed

    private void jButtonBuscar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscar1ActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscar1ActionPerformed
        if (this.camposVaciosA())
        JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        else
        try
        {
            this.hash1 = controlador.ubicarAlumno(this.jTextFieldNombre1.getText(), this.jTextFieldApellido1.getText());
            this.listar1(hash1);
        } catch (NoEstaEntidadException e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscar1ActionPerformed

    private void jButtonElegir1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonElegir1ActionPerformed
    {//GEN-HEADEREND:event_jButtonElegir1ActionPerformed
        int index, i;
        Iterator <Alumno> iA;

        if (this.camposVaciosA())
        JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
        if (this.jList1.getSelectedValue() != null)
        {
            index = this.jList1.getSelectedIndex();
            iA = this.hash1.values().iterator();
            i = 0;
            while (iA.hasNext() && i < index)
            {
                iA.next();
                i++;
            }
            if (iA.hasNext())
            {
                this.alumno = iA.next();
                JOptionPane.showMessageDialog(rootPane, "Se ha seleccionado al alumno");
            }
        }
        else
        JOptionPane.showMessageDialog(rootPane, "Seleccione un elemento de la lista", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonElegir1ActionPerformed

    private void jButtonBuscar2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscar2ActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscar2ActionPerformed
        if (this.camposVaciosC())
        JOptionPane.showMessageDialog(rootPane, "Falta completar el campo", "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        else
        try
        {
            this.hash2 = controlador.ubicarCursada(this.jTextFieldNombre2.getText());
            this.listar2(hash2);
        } catch (NoEstaEntidadException e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscar2ActionPerformed

    private void jButtonElegir2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonElegir2ActionPerformed
    {//GEN-HEADEREND:event_jButtonElegir2ActionPerformed
        int index, i;
        Iterator <Cursada> iC;

        if (this.camposVaciosC())
        JOptionPane.showMessageDialog(rootPane, "Faltan completar el campo", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
        if (this.jList2.getSelectedValue() != null)
        {
            index = this.jList2.getSelectedIndex();
            iC = this.hash2.values().iterator();
            i = 0;
            while (iC.hasNext() && i < index)
            {
                iC.next();
                i++;
            }
            if (iC.hasNext())
            {
                this.cursada = iC.next();
                JOptionPane.showMessageDialog(rootPane, "Se ha seleccionado a la cursada");
            }
        }
        else
        JOptionPane.showMessageDialog(rootPane, "Seleccione un elemento de la lista", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonElegir2ActionPerformed

    private void jButtonDarAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDarAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonDarAltaActionPerformed
        if (this.camposVaciosA() || this.camposVaciosC())
        JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
        if (this.jList1.getSelectedValue() == null || this.jList2.getSelectedValue() == null)
        JOptionPane.showMessageDialog(rootPane, "Seleccione un alumno y/o una cursada de las listas", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
        {
            try
            {
                this.controlador.altaAlumnoACursada(this.alumno, this.cursada);
                JOptionPane.showMessageDialog(rootPane, "Alta de Alumno a la Cursada Exitosa");
                this.dispose();
            } catch (EntidadNoAptaParaCursadaException e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonDarAltaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelarActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(AlumnoAltaACursada2.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(AlumnoAltaACursada2.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(AlumnoAltaACursada2.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(AlumnoAltaACursada2.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    AlumnoAltaACursada2 dialog = new AlumnoAltaACursada2(new javax.swing.JFrame(), true, null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter()
                    {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e)
                        {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar1;
    private javax.swing.JButton jButtonBuscar2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDarAlta;
    private javax.swing.JButton jButtonElegir1;
    private javax.swing.JButton jButtonElegir2;
    private javax.swing.JLabel jLabelAlumno;
    private javax.swing.JLabel jLabelAlumnoAlta1;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelCursada;
    private javax.swing.JLabel jLabelCursadaAlta1;
    private javax.swing.JLabel jLabelDatosAlumnoAlta1;
    private javax.swing.JLabel jLabelDatosCursadaAlta1;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNombre2;
    // End of variables declaration//GEN-END:variables

}
