
package gui;

import exceptions.EntidadNoAptaParaCursadaException;
import exceptions.NoEstaEntidadException;

import java.awt.Dimension;
import java.awt.Toolkit;

import java.util.HashMap;

import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

import pga.Alumno;
import pga.Controlador;
import pga.Cursada;

/**
 *
 * @author DELL
 */
public class AlumnoBajaACursada extends javax.swing.JDialog
{
    private Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    private Controlador controlador;
    private HashMap<String, Alumno> hash1;
    private HashMap<String, Cursada> hash2;
    private DefaultListModel listModel1, listModel2;
    private Alumno alumno;    
    private Cursada cursada;

    /** Creates new form AlumnoBajaACursada */
    public AlumnoBajaACursada(java.awt.Frame parent, boolean modal, Controlador controlador)
    {
        super(parent, modal);
        this.controlador = controlador;
        this.setTitle("Alumno - Baja de Cursada");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setResizable(false);
        initComponents();
        this.setLocation(d.width / 2 - this.getWidth() / 2, d.height / 2 - this.getHeight() / 2);
        this.setVisible(true);
    }

    public boolean camposVaciosA()
    {
        return !(this.jTextFieldNombre1.getText().length() != 0 && this.jTextFieldApellido1.getText().length() != 0);
    }
   
    public void listar1(HashMap<String, Alumno> hash)
    {
        Iterator <Alumno> iA = hash.values().iterator();
        
        this.listModel1.clear();
        while(iA.hasNext())
            this.listModel1.addElement(iA.next());
    }
    
    public boolean camposVaciosC()
    {
        return this.jTextFieldNombre2.getText().length() == 0;
    }
    
    public void listar2(HashMap<String, Cursada> hash)
    {
        Iterator <Cursada> iC = hash.values().iterator();
        
        this.listModel2.clear();
        while(iC.hasNext())
            this.listModel2.addElement(iC.next());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombreA = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jButtonBuscarA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listModel1 = new DefaultListModel();
        jList1 = new javax.swing.JList<>(listModel1);
        jButtonElegirA = new javax.swing.JButton();
        jLabelAlumno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombreC = new javax.swing.JLabel();
        jTextFieldNombre2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listModel2 = new DefaultListModel();
        jList2 = new javax.swing.JList<>(listModel2);
        jButtonBuscarC = new javax.swing.JButton();
        jButtonElegirC = new javax.swing.JButton();
        jLabelCursada = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelAlumnoBaja = new javax.swing.JLabel();
        jLabelDatosAlumnoBaja = new javax.swing.JLabel();
        jLabelCursadaBaja = new javax.swing.JLabel();
        jLabelDatosCursadaBaja = new javax.swing.JLabel();
        jButtonBaja = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombreA.setText("Nombre");

        jLabelApellido.setText("Apellido");

        jTextFieldApellido1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldApellido1ActionPerformed(evt);
            }
        });

        jButtonBuscarA.setText("Buscar");
        jButtonBuscarA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarAActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jButtonElegirA.setText("Elegir");
        jButtonElegirA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonElegirAActionPerformed(evt);
            }
        });

        jLabelAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAlumno.setText("Alumnos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonBuscarA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombreA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonElegirA)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonElegirA)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreA)
                            .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelApellido))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarA)))
                .addGap(28, 28, 28))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombreC.setText("Nombre");

        jScrollPane2.setViewportView(jList2);

        jButtonBuscarC.setText("Buscar");
        jButtonBuscarC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarCActionPerformed(evt);
            }
        });

        jButtonElegirC.setText("Elegir");
        jButtonElegirC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonElegirCActionPerformed(evt);
            }
        });

        jLabelCursada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCursada.setText("Cursadas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelNombreC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonElegirC)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCursada)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCursada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreC))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarC)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonElegirC)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAlumnoBaja.setText("Alumno");

        jLabelDatosAlumnoBaja.setText("Elija un alumno");

        jLabelCursadaBaja.setText("Cursada");

        jLabelDatosCursadaBaja.setText("Elija una cursada");

        jButtonBaja.setText("Dar baja");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlumnoBaja)
                    .addComponent(jLabelCursadaBaja))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDatosAlumnoBaja)
                    .addComponent(jLabelDatosCursadaBaja))
                .addGap(58, 58, 58)
                .addComponent(jButtonBaja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAlumnoBaja)
                            .addComponent(jLabelDatosAlumnoBaja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCursadaBaja)
                            .addComponent(jLabelDatosCursadaBaja)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonBaja)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCancelar)
                .addContainerGap(332, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(514, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        pack();
    }//GEN-END:initComponents

    private void jTextFieldApellido1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldApellido1ActionPerformed
    {//GEN-HEADEREND:event_jTextFieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido1ActionPerformed

    private void jButtonBuscarAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarAActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarAActionPerformed
        if (this.camposVaciosA())
            JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        else
            try
            {
                this.hash1 = controlador.ubicarAlumno(this.jTextFieldNombre1.getText(), this.jTextFieldApellido1.getText());
                this.listar1(hash1);
            } catch (NoEstaEntidadException e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButtonBuscarAActionPerformed

    private void jButtonElegirAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonElegirAActionPerformed
    {//GEN-HEADEREND:event_jButtonElegirAActionPerformed
    int index;

    if (this.camposVaciosA())
        JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Baja a Cursada", JOptionPane.WARNING_MESSAGE);
    else
        if (this.jList1.getSelectedValue() != null)
        {
            index = this.jList1.getSelectedIndex();
            this.alumno = (Alumno) this.listModel1.getElementAt(index);
            JOptionPane.showMessageDialog(rootPane, "Se ha seleccionado al alumno");
            this.jLabelDatosAlumnoBaja.setText(this.alumno.getNombre() + " " + this.alumno.getNombre());
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Seleccione un elemento de la lista", "Error de Baja a Cursada", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonElegirAActionPerformed

    private void jButtonBuscarCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarCActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarCActionPerformed
        if (this.camposVaciosC())
            JOptionPane.showMessageDialog(rootPane, "Falta completar el campo", "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        else
            try
            {
                this.hash2 = controlador.ubicarCursada(this.jTextFieldNombre2.getText());
                this.listar2(hash2);
            } catch (NoEstaEntidadException e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButtonBuscarCActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonBajaActionPerformed
        if (this.camposVaciosA() || this.camposVaciosC())
            JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
            if (this.jList1.getSelectedValue() == null || this.jList2.getSelectedValue() == null)
                JOptionPane.showMessageDialog(rootPane, "Seleccione un alumno y/o una cursada de las listas", "Error de Baja a Cursada", JOptionPane.WARNING_MESSAGE);
            else
            {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea dar de baja al alumno en la cursada?", "Alumno - Baja A Cursada", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                    try
                    {
                        this.controlador.bajaAlumnoDeCursada(this.alumno, this.cursada);
                        JOptionPane.showMessageDialog(rootPane, "Baja de Alumno de la Cursada Exitosa");
                        this.dispose();
                    } catch (NoEstaEntidadException e)
                    {
                        JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Baja de Cursada", JOptionPane.WARNING_MESSAGE);
                    }
            }
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonElegirCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonElegirCActionPerformed
    {//GEN-HEADEREND:event_jButtonElegirCActionPerformed
        int index;

        if (this.camposVaciosC())
            JOptionPane.showMessageDialog(rootPane, "Faltan completar el campo", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
            if (this.jList2.getSelectedValue() != null)
            {
                index = this.jList2.getSelectedIndex();
                this.cursada = (Cursada) this.listModel2.getElementAt(index);
                JOptionPane.showMessageDialog(rootPane, "Se ha seleccionado a la cursada");
                this.jLabelDatosCursadaBaja.setText(this.cursada.getNombre());
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Seleccione un elemento de la lista", "Error de Baja de Cursada", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonElegirCActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelarActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(AlumnoBajaACursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(AlumnoBajaACursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(AlumnoBajaACursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(AlumnoBajaACursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    AlumnoBajaACursada dialog = new AlumnoBajaACursada(new javax.swing.JFrame(), true, null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter()
                    {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e)
                        {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonBuscarA;
    private javax.swing.JButton jButtonBuscarC;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonElegirA;
    private javax.swing.JButton jButtonElegirC;
    private javax.swing.JLabel jLabelAlumno;
    private javax.swing.JLabel jLabelAlumnoBaja;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCursada;
    private javax.swing.JLabel jLabelCursadaBaja;
    private javax.swing.JLabel jLabelDatosAlumnoBaja;
    private javax.swing.JLabel jLabelDatosCursadaBaja;
    private javax.swing.JLabel jLabelNombreA;
    private javax.swing.JLabel jLabelNombreC;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNombre2;
    // End of variables declaration//GEN-END:variables

}
