
package gui;

import exceptions.EntidadNoAptaParaCursadaException;
import exceptions.NoEstaEntidadException;

import java.awt.Dimension;
import java.awt.Toolkit;

import java.util.HashMap;
import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

import pga.Alumno;
import pga.Controlador;
import pga.Cursada;
import pga.Profesor;

/**
 *
 * @author DELL
 */
public class ProfesorAltaACursada extends javax.swing.JDialog
{
    private Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    private Controlador controlador;
    private DefaultListModel listModel1, listModel2;
    private HashMap<String, Profesor> hash1;
    private HashMap<String, Cursada> hash2;
    private Profesor profesor;
    private Cursada cursada;

    /** Creates new form ProfesorAltaACursada */
    public ProfesorAltaACursada(Controlador controlador)
    {
        this.controlador = controlador;
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocation(d.width / 2 - this.getWidth() / 2, d.height / 2 - this.getHeight() / 2);
        this.setVisible(true);
    }

    public boolean camposVaciosP()
    {
        return !(this.jTextFieldNombreP.getText().length() != 0 && this.jTextFieldApellido.getText().length() != 0);
    }
    
    public void listar1(HashMap<String, Profesor> hash)
    {
        Iterator <Profesor> iA = hash.values().iterator();
        
        this.listModel1.clear();
        while(iA.hasNext())
            this.listModel1.addElement(iA.next());
    }
    
    public boolean camposVaciosC()
    {
        return this.jTextFieldNombreC.getText().length() == 0;
    }
    
    public void listar2(HashMap<String, Cursada> hash)
    {
        Iterator <Cursada> iC = hash.values().iterator();
        
        this.listModel2.clear();
        while(iC.hasNext())
            this.listModel2.addElement(iC.next());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombreP = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldNombreP = new javax.swing.JTextField();
        jButtonBuscarP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listModel1 = new DefaultListModel();
        jListP = new javax.swing.JList<>(listModel1);
        jButtonElegirP = new javax.swing.JButton();
        jLabelProfesor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombreC = new javax.swing.JLabel();
        jTextFieldNombreC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listModel2 = new DefaultListModel();
        jListC = new javax.swing.JList<>(listModel2);
        jButtonBuscarC = new javax.swing.JButton();
        jButtonElegirC = new javax.swing.JButton();
        jLabelCursada = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelProfesorAlta = new javax.swing.JLabel();
        jLabelDatosProfesorAlta = new javax.swing.JLabel();
        jLabelCursadaAlta = new javax.swing.JLabel();
        jLabelDatosCursadaAlta = new javax.swing.JLabel();
        jButtonAlta = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombreP.setText("Nombre");

        jLabelApellido.setText("Apellido");

        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldApellidoActionPerformed(evt);
            }
        });

        jButtonBuscarP.setText("Buscar");
        jButtonBuscarP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarPActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListP);

        jButtonElegirP.setText("Elegir");
        jButtonElegirP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonElegirPActionPerformed(evt);
            }
        });

        jLabelProfesor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProfesor.setText("Profesores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonBuscarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombreP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreP))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonElegirP)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonElegirP)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreP)
                            .addComponent(jTextFieldNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelApellido))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarP)))
                .addGap(28, 28, 28))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombreC.setText("Nombre");

        jScrollPane2.setViewportView(jListC);

        jButtonBuscarC.setText("Buscar");
        jButtonBuscarC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarCActionPerformed(evt);
            }
        });

        jButtonElegirC.setText("Elegir");
        jButtonElegirC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonElegirCActionPerformed(evt);
            }
        });

        jLabelCursada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCursada.setText("Cursadas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelNombreC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombreC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonElegirC)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCursada)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCursada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreC))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarC)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonElegirC)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelProfesorAlta.setText("Profesor");

        jLabelDatosProfesorAlta.setText("Elija un profesor");

        jLabelCursadaAlta.setText("Cursada");

        jLabelDatosCursadaAlta.setText("Elija una cursada");

        jButtonAlta.setText("Dar alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProfesorAlta)
                    .addComponent(jLabelCursadaAlta))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDatosProfesorAlta)
                    .addComponent(jLabelDatosCursadaAlta))
                .addGap(58, 58, 58)
                .addComponent(jButtonAlta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProfesorAlta)
                            .addComponent(jLabelDatosProfesorAlta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCursadaAlta)
                            .addComponent(jLabelDatosCursadaAlta)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonAlta)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldApellidoActionPerformed
    {//GEN-HEADEREND:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jButtonBuscarPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarPActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarPActionPerformed
        if (this.camposVaciosP())
        JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        else
            try
            {
                this.hash1 = controlador.ubicarProfesor(this.jTextFieldNombreP.getText(), this.jTextFieldApellido.getText());
                this.listar1(hash1);
            } catch (NoEstaEntidadException e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButtonBuscarPActionPerformed

    private void jButtonElegirPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonElegirPActionPerformed
    {//GEN-HEADEREND:event_jButtonElegirPActionPerformed
        int index;

        if (this.camposVaciosP())
            JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
            if (this.jListP.getSelectedValue() != null)
            {
                index = this.jListP.getSelectedIndex();
                this.profesor = (Profesor) this.listModel1.getElementAt(index);
                JOptionPane.showMessageDialog(rootPane, "Se ha seleccionado al alumno");
                this.jLabelDatosProfesorAlta.setText(this.profesor.getNombre() + " " + this.profesor.getNombre());
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Seleccione un elemento de la lista", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonElegirPActionPerformed

    private void jButtonBuscarCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarCActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarCActionPerformed
        if (this.camposVaciosC())
            JOptionPane.showMessageDialog(rootPane, "Falta completar el campo", "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        else
            try
            {
                this.hash2 = controlador.ubicarCursada(this.jTextFieldNombreC.getText());
                this.listar2(hash2);
            } catch (NoEstaEntidadException e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButtonBuscarCActionPerformed

    private void jButtonElegirCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonElegirCActionPerformed
    {//GEN-HEADEREND:event_jButtonElegirCActionPerformed
        int index;

        if (this.camposVaciosC())
            JOptionPane.showMessageDialog(rootPane, "Faltan completar el campo", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
            if (this.jListC.getSelectedValue() != null)
            {
                index = this.jListC.getSelectedIndex();
                this.cursada = (Cursada) this.listModel2.getElementAt(index);
                JOptionPane.showMessageDialog(rootPane, "Se ha seleccionado a la cursada");
                this.jLabelDatosCursadaAlta.setText(this.cursada.getNombre());
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Seleccione un elemento de la lista", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonElegirCActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonAltaActionPerformed
        if (this.camposVaciosP() || this.camposVaciosC())
            JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
        else
            if (this.jListP.getSelectedValue() == null || this.jListC.getSelectedValue() == null)
                JOptionPane.showMessageDialog(rootPane, "Seleccione un alumno y/o una cursada de las listas", "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
            else
            {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea dar de alta al profesor en la cursada?", "Profesor - Alta A Cursada", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                    try
                    {
                        this.controlador.altaProfesorACursada(this.profesor, this.cursada);
                        JOptionPane.showMessageDialog(rootPane, "Alta de Profesor a la Cursada Exitosa");
                        this.dispose();
                    } catch (EntidadNoAptaParaCursadaException e)
                    {
                        JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de Alta a Cursada", JOptionPane.WARNING_MESSAGE);
                    }
            }
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelarActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(ProfesorAltaACursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(ProfesorAltaACursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(ProfesorAltaACursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(ProfesorAltaACursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    new ProfesorAltaACursada(null).setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBuscarC;
    private javax.swing.JButton jButtonBuscarP;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonElegirC;
    private javax.swing.JButton jButtonElegirP;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCursada;
    private javax.swing.JLabel jLabelCursadaAlta;
    private javax.swing.JLabel jLabelDatosCursadaAlta;
    private javax.swing.JLabel jLabelDatosProfesorAlta;
    private javax.swing.JLabel jLabelNombreC;
    private javax.swing.JLabel jLabelNombreP;
    private javax.swing.JLabel jLabelProfesor;
    private javax.swing.JLabel jLabelProfesorAlta;
    private javax.swing.JList<String> jListC;
    private javax.swing.JList<String> jListP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNombreC;
    private javax.swing.JTextField jTextFieldNombreP;
    // End of variables declaration//GEN-END:variables

}
